# Generated by Django 2.0.2 on 2018-05-29 07:37

from django.db import migrations, models
import space.models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField(default=space.models.uuid_default)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('author', models.CharField(default='', max_length=30)),
                ('datetime', models.DateField()),
                ('text', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
