# Generated by Django 2.0.2 on 2018-05-29 07:52

from django.db import migrations, models
import space.models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_messageboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='userId',
        ),
        migrations.AddField(
            model_name='messageboard',
            name='parentReplyId',
            field=models.UUIDField(default=space.models.uuid_default, editable=False),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='replyId',
            field=models.UUIDField(default=space.models.uuid_default, editable=False),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='userName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='id',
            field=models.UUIDField(default=space.models.uuid_default, editable=False, primary_key=True, serialize=False),
        ),
    ]
