# Generated by Django 2.0.2 on 2018-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_auto_20180529_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='parentReplyId',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
