# Generated by Django 2.0.2 on 2018-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_auto_20180529_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageboard',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
